package yugioh.ui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

/*
Ventana principal del duelo: controles arriba, cartas de la máquina y del
jugador en el centro y log de batalla a la derecha.

El diseño está en MainWindow.form (IntelliJ GUI Designer). A partir de ese
rchivo IntelliJ genera automáticamente el método $$$setupUI$$$(), que:

 Crea mainPanel con BorderLayout y tamaño preferido de 1000 x 800 px.
 NORTH: topPanel (FlowLayout centrado) con el botón y las etiquetas de estado.
 CENTER: boardPanel (GridBagLayout) con dos filas que ocupan todo el espacio:
 fila 0 las cartas de la máquina y fila 1 las del jugador. Cada fila es un
 panel FlowLayout con borde titulado y 3 CardPanel anidados.
 EAST: scrollLog (320 px de ancho) que contiene el área de texto del log.

 No se debe editar $$$setupUI$$$() a mano: se reescribe al guardar el .form.
 */
public class MainWindow {
    /*Panel raíz de la ventana. */
    private JPanel mainPanel;

    // ---- Zona superior: controles y estado del duelo ----
    /*Panel superior que agrupa el botón y las etiquetas. */
    private JPanel topPanel;
    /*Botón "Iniciar duelo". */
    private JButton btnIniciarDuelo;
    /*Puntaje acumulado: "Jugador X - Y Máquina". */
    private JLabel lblPuntaje;
    /*Anuncio del ganador final del duelo (vacío mientras se juega). */
    private JLabel lblGanador;
    /*Mensajes de error visibles: "No se pudo cargar la carta", "error de red". */
    private JLabel lblEstado;

    // ---- Zona central: tablero con las cartas ----
    /*Contenedor de las dos filas de cartas. */
    private JPanel boardPanel;
    /*Fila con las 3 cartas de la máquina. */
    private JPanel aiCardsPanel;
    /*Cartas de la máquina (formulario CardPanel anidado). */
    private CardPanel aiCard1;
    private CardPanel aiCard2;
    private CardPanel aiCard3;
    /*Fila con las 3 cartas del jugador. */
    private JPanel playerCardsPanel;
    /*Cartas del jugador (formulario CardPanel anidado). */
    private CardPanel playerCard1;
    private CardPanel playerCard2;
    private CardPanel playerCard3;

    // ---- Zona derecha: log de batalla ----
    /** Barra de desplazamiento del log (JScrollPane). */
    private JScrollPane scrollLog;
    /*Log de batalla: quién jugó qué carta, resultado del turno y puntaje. Solo lectura. */
    private JTextArea txtLog;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setPreferredSize(new Dimension(1000, 800));
        topPanel = new JPanel();
        topPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 15, 5));
        mainPanel.add(topPanel, BorderLayout.NORTH);
        btnIniciarDuelo = new JButton();
        btnIniciarDuelo.setText("Iniciar duelo");
        topPanel.add(btnIniciarDuelo);
        lblPuntaje = new JLabel();
        lblPuntaje.setText("Jugador 0 - 0 Máquina");
        topPanel.add(lblPuntaje);
        lblGanador = new JLabel();
        lblGanador.setText("");
        topPanel.add(lblGanador);
        lblEstado = new JLabel();
        lblEstado.setText("");
        topPanel.add(lblEstado);
        boardPanel = new JPanel();
        boardPanel.setLayout(new GridBagLayout());
        mainPanel.add(boardPanel, BorderLayout.CENTER);
        aiCardsPanel = new JPanel();
        aiCardsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        boardPanel.add(aiCardsPanel, gbc);
        aiCardsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Cartas de la máquina", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        aiCard1 = new CardPanel();
        aiCardsPanel.add(aiCard1.$$$getRootComponent$$$());
        aiCard2 = new CardPanel();
        aiCardsPanel.add(aiCard2.$$$getRootComponent$$$());
        aiCard3 = new CardPanel();
        aiCardsPanel.add(aiCard3.$$$getRootComponent$$$());
        playerCardsPanel = new JPanel();
        playerCardsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        boardPanel.add(playerCardsPanel, gbc);
        playerCardsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Tus cartas", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        playerCard1 = new CardPanel();
        playerCardsPanel.add(playerCard1.$$$getRootComponent$$$());
        playerCard2 = new CardPanel();
        playerCardsPanel.add(playerCard2.$$$getRootComponent$$$());
        playerCard3 = new CardPanel();
        playerCardsPanel.add(playerCard3.$$$getRootComponent$$$());
        scrollLog = new JScrollPane();
        scrollLog.setPreferredSize(new Dimension(320, 0));
        mainPanel.add(scrollLog, BorderLayout.EAST);
        scrollLog.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Log de batalla", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        txtLog = new JTextArea();
        txtLog.setEditable(false);
        txtLog.setLineWrap(true);
        txtLog.setWrapStyleWord(true);
        scrollLog.setViewportView(txtLog);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
