package yugioh.ui;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import yugioh.api.YgoApiClient;
import yugioh.listener.BattleListener;
import yugioh.logic.Duel;
import yugioh.model.Card;

/*
Ventana principal del duelo: controles arriba, cartas de la máquina y del
jugador en el centro y log de batalla a la derecha.

El diseño está en MainWindow.form (IntelliJ GUI Designer). A partir de ese
rchivo IntelliJ genera automáticamente el método $$$setupUI$$$(), que:

 Crea mainPanel con BorderLayout y tamaño preferido de 1000 x 800 px.
 NORTH: topPanel (FlowLayout centrado) con el botón y las etiquetas de estado.
 CENTER: boardPanel (GridBagLayout) con dos filas que ocupan todo el espacio:
 fila 0 las cartas de la máquina y fila 1 las del jugador. Cada fila es un
 panel FlowLayout con borde titulado y 3 CardPanel anidados.
 EAST: scrollLog (320 px de ancho) que contiene el área de texto del log.

 No se debe editar $$$setupUI$$$() a mano: se reescribe al guardar el .form.
 */
public class MainWindow implements BattleListener {
    /*Panel raíz de la ventana. */
    private JPanel mainPanel;

    // ---- Zona superior: controles y estado del duelo ----
    /*Panel superior que agrupa el botón y las etiquetas. */
    private JPanel topPanel;
    /*Botón "Iniciar duelo". */
    private JButton btnIniciarDuelo;
    /*Puntaje acumulado: "Jugador X - Y Máquina". */
    private JLabel lblPuntaje;
    /*Anuncio del ganador final del duelo (vacío mientras se juega). */
    private JLabel lblGanador;
    /*Mensajes de error visibles: "No se pudo cargar la carta", "error de red". */
    private JLabel lblEstado;

    // ---- Zona central: tablero con las cartas ----
    /*Contenedor de las dos filas de cartas. */
    private JPanel boardPanel;
    /*Fila con las 3 cartas de la máquina. */
    private JPanel aiCardsPanel;
    /*Cartas de la máquina (formulario CardPanel anidado). */
    private CardPanel aiCard1;
    private CardPanel aiCard2;
    private CardPanel aiCard3;
    /*Fila con las 3 cartas del jugador. */
    private JPanel playerCardsPanel;
    /*Cartas del jugador (formulario CardPanel anidado). */
    private CardPanel playerCard1;
    private CardPanel playerCard2;
    private CardPanel playerCard3;

    // ---- Zona derecha: log de batalla ----
    /** Barra de desplazamiento del log (JScrollPane). */
    private JScrollPane scrollLog;
    /*Log de batalla: quién jugó qué carta, resultado del turno y puntaje. Solo lectura. */
    private JTextArea txtLog;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setPreferredSize(new Dimension(1000, 800));
        topPanel = new JPanel();
        topPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 15, 5));
        mainPanel.add(topPanel, BorderLayout.NORTH);
        btnIniciarDuelo = new JButton();
        btnIniciarDuelo.setText("Iniciar duelo");
        topPanel.add(btnIniciarDuelo);
        lblPuntaje = new JLabel();
        lblPuntaje.setText("Jugador 0 - 0 Máquina");
        topPanel.add(lblPuntaje);
        lblGanador = new JLabel();
        lblGanador.setText("");
        topPanel.add(lblGanador);
        lblEstado = new JLabel();
        lblEstado.setText("");
        topPanel.add(lblEstado);
        boardPanel = new JPanel();
        boardPanel.setLayout(new GridBagLayout());
        mainPanel.add(boardPanel, BorderLayout.CENTER);
        aiCardsPanel = new JPanel();
        aiCardsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        boardPanel.add(aiCardsPanel, gbc);
        aiCardsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Cartas de la máquina", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        aiCard1 = new CardPanel();
        aiCardsPanel.add(aiCard1.$$$getRootComponent$$$());
        aiCard2 = new CardPanel();
        aiCardsPanel.add(aiCard2.$$$getRootComponent$$$());
        aiCard3 = new CardPanel();
        aiCardsPanel.add(aiCard3.$$$getRootComponent$$$());
        playerCardsPanel = new JPanel();
        playerCardsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        boardPanel.add(playerCardsPanel, gbc);
        playerCardsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Tus cartas", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        playerCard1 = new CardPanel();
        playerCardsPanel.add(playerCard1.$$$getRootComponent$$$());
        playerCard2 = new CardPanel();
        playerCardsPanel.add(playerCard2.$$$getRootComponent$$$());
        playerCard3 = new CardPanel();
        playerCardsPanel.add(playerCard3.$$$getRootComponent$$$());
        scrollLog = new JScrollPane();
        scrollLog.setPreferredSize(new Dimension(320, 0));
        mainPanel.add(scrollLog, BorderLayout.EAST);
        scrollLog.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Log de batalla", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        txtLog = new JTextArea();
        txtLog.setEditable(false);
        txtLog.setLineWrap(true);
        txtLog.setWrapStyleWord(true);
        scrollLog.setViewportView(txtLog);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    // ---- Comportamiento (fuera del código generado por el diseñador) ----

    private final YgoApiClient api = new YgoApiClient();
    private CardPanel[] playerPanels;
    private CardPanel[] aiPanels;
    private JRadioButton rbAtaque;
    private JRadioButton rbDefensa;
    private Duel duel;
    private int ronda;

    /* Datos que se descargan en segundo plano antes de empezar el duelo. */
    private static class LoadedCards {
        final List<Card> playerCards = new ArrayList<>();
        final List<Card> aiCards = new ArrayList<>();
        final List<ImageIcon> playerImages = new ArrayList<>();
        final List<ImageIcon> aiImages = new ArrayList<>();
    }

    /* Una carta ya descargada junto con su imagen (la imagen puede ser null). */
    private static class LoadedCard {
        final Card card;
        final ImageIcon image;

        LoadedCard(Card card, ImageIcon image) {
            this.card = card;
            this.image = image;
        }
    }

    public MainWindow() {
        playerPanels = new CardPanel[]{playerCard1, playerCard2, playerCard3};
        aiPanels = new CardPanel[]{aiCard1, aiCard2, aiCard3};

        // El enunciado pide ataque/defensa: se elige con estos botones antes de elegir la carta
        rbAtaque = new JRadioButton("Ataque", true);
        rbDefensa = new JRadioButton("Defensa");
        ButtonGroup modo = new ButtonGroup();
        modo.add(rbAtaque);
        modo.add(rbDefensa);
        topPanel.add(new JLabel("Modo:"));
        topPanel.add(rbAtaque);
        topPanel.add(rbDefensa);
        lblGanador.setFont(lblGanador.getFont().deriveFont(Font.BOLD, 16f));
        lblEstado.setText("Pulsa \"Iniciar duelo\" para empezar.");

        for (CardPanel panel : aiPanels) {
            panel.setChooseVisible(false); // la máquina elige sola
            panel.clear();
        }
        for (CardPanel panel : playerPanels) {
            panel.clear();
            panel.addChooseListener(e -> elegirCarta(panel)); // ActionListener "Elegir carta"
        }
        btnIniciarDuelo.addActionListener(e -> iniciarDuelo()); // ActionListener "Iniciar duelo"
    }

    /* Crea el JFrame, le pone el panel principal y lo muestra. */
    public void mostrar() {
        JFrame frame = new JFrame("Yu-Gi-Oh! Duel Lite");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        mainPanel.setPreferredSize(new Dimension(960, 640));
        frame.setContentPane(mainPanel);
        frame.pack();
        // Nunca más grande que la pantalla disponible
        Rectangle pantalla = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        frame.setSize(Math.min(frame.getWidth(), pantalla.width), Math.min(frame.getHeight(), pantalla.height));
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    /* Descarga 3 cartas por bando SIN bloquear el hilo de la interfaz (SwingWorker). */
    private void iniciarDuelo() {
        btnIniciarDuelo.setEnabled(false);
        txtLog.setText("");
        lblGanador.setText("");
        lblPuntaje.setText("Jugador 0 - 0 Máquina");
        lblEstado.setForeground(UIManager.getColor("Label.foreground"));
        lblEstado.setText("Cargando cartas...");
        for (CardPanel panel : playerPanels) panel.clear();
        for (CardPanel panel : aiPanels) panel.clear();
        duel = null;

        new SwingWorker<LoadedCards, Void>() {
            @Override
            protected LoadedCards doInBackground() throws Exception {
                // Las 6 cartas no dependen entre sí: se piden a la vez para que cargue más rápido
                ExecutorService pool = Executors.newFixedThreadPool(6);
                try {
                    List<Future<LoadedCard>> futures = new ArrayList<>();
                    for (int i = 0; i < 6; i++) {
                        futures.add(pool.submit(() -> {
                            Card card = api.getRandomMonster();
                            return new LoadedCard(card, cargarImagen(card.getImageUrl()));
                        }));
                    }
                    LoadedCards data = new LoadedCards();
                    for (int i = 0; i < 6; i++) {
                        LoadedCard loaded = futures.get(i).get();
                        // Las 3 primeras son del jugador y las 3 últimas de la máquina
                        (i < 3 ? data.playerCards : data.aiCards).add(loaded.card);
                        (i < 3 ? data.playerImages : data.aiImages).add(loaded.image);
                    }
                    return data;
                } catch (ExecutionException e) {
                    // Se relanza la causa real (p. ej. IOException) para mostrar el error correcto
                    if (e.getCause() instanceof Exception) throw (Exception) e.getCause();
                    throw e;
                } finally {
                    pool.shutdownNow();
                }
            }

            @Override
            protected void done() {
                try {
                    empezarDuelo(get());
                } catch (ExecutionException e) {
                    mostrarError(e.getCause());
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    mostrarError(e);
                }
            }
        }.execute();
    }

    /* Descarga la imagen; si falla devuelve null y la carta se muestra sin imagen. */
    private ImageIcon cargarImagen(String url) {
        try {
            BufferedImage img = ImageIO.read(URI.create(url).toURL());
            return img == null ? null : new ImageIcon(img);
        } catch (IOException e) {
            return null;
        }
    }

    /* Ya están las 6 cartas: se muestran y se crea el duelo. */
    private void empezarDuelo(LoadedCards data) {
        duel = new Duel(data.playerCards, data.aiCards, this);
        ronda = 0;
        for (int i = 0; i < 3; i++) {
            playerPanels[i].showCard(data.playerCards.get(i), data.playerImages.get(i));
            playerPanels[i].setChooseEnabled(true);
            aiPanels[i].showCard(data.aiCards.get(i), data.aiImages.get(i));
        }
        lblEstado.setText("Elige el modo y una de tus cartas.");
        txtLog.append("Duelo iniciado. Empieza: "
                + (duel.isPlayerStarts() ? Duel.PLAYER : Duel.AI) + "\n\n");
    }

    /* Se pulsó "Elegir carta" en una de las cartas del jugador. */
    private void elegirCarta(CardPanel panel) {
        if (duel == null || duel.isFinished()) return;
        panel.markUsed();
        duel.playRound(panel.getCard(), rbAtaque.isSelected());

        // La carta que la máquina ya jugó deja de estar en su mano: se pone en gris
        for (CardPanel ai : aiPanels) {
            if (ai.getCard() != null && !duel.getAiHand().contains(ai.getCard())) {
                ai.markUsed();
            }
        }
    }

    /* Error visible: "No se pudo cargar la carta" / "error de red". */
    private void mostrarError(Throwable error) {
        String detalle = error.getMessage() == null ? error.toString() : error.getMessage();
        String mensaje = (error instanceof IOException)
                ? "No se pudo cargar la carta (error de red): " + detalle
                : "No se pudo cargar la carta: " + detalle;
        lblEstado.setForeground(Color.RED);
        lblEstado.setText(mensaje);
        btnIniciarDuelo.setEnabled(true);
        JOptionPane.showMessageDialog(mainPanel, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    // ---- BattleListener: la lógica avisa y la ventana pinta ----

    @Override
    public void onTurn(String playerCard, String aiCard, String winner) {
        ronda++;
        txtLog.append("--- Ronda " + ronda + " ---\n"
                + "Jugador: " + playerCard + "\n"
                + "Máquina: " + aiCard + "\n"
                + "Resultado: " + (Duel.DRAW.equals(winner) ? "empate" : "gana " + winner) + "\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    @Override
    public void onScoreChanged(int playerScore, int aiScore) {
        lblPuntaje.setText("Jugador " + playerScore + " - " + aiScore + " Máquina");
        txtLog.append("Marcador: Jugador " + playerScore + " - " + aiScore + " Máquina\n\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    @Override
    public void onDuelEnded(String winner) {
        String texto = Duel.DRAW.equals(winner) ? "¡Empate!" : "¡Ganador: " + winner + "!";
        lblGanador.setText(texto);
        lblEstado.setText("Duelo terminado.");
        txtLog.append("=== " + texto + " ===\n");
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
        for (CardPanel panel : playerPanels) panel.setChooseEnabled(false);
        btnIniciarDuelo.setEnabled(true);
    }

}
